name: Expo CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm test

      - name: 🚀 Publish to Expo
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: eas update --auto

      - name: 🏗 Build for Android
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: eas build --platform android --non-interactive

      - name: 🏗 Build for iOS
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: eas build --platform ios --non-interactive

      - name: 🌐 Build Web Version
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx expo build:web

      - name: 🚀 Deploy to GitHub Pages
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-build
